//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.225.
// 
#pragma warning disable 1591

namespace TSN.Presentable.Services.DocumentConverterServiceReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DocumentConverterSoap", Namespace="http://schema.tenseventynine.com/PresentableServices/DocumentConverter/2011/05")]
    public partial class DocumentConverter : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RenderAsPdfOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DocumentConverter() {
            this.Url = global::TSN.Presentable.Services.Properties.Settings.Default.DocumentConversionService_DocumentConversionServiceReference_DocumentConverter1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RenderAsPdfCompletedEventHandler RenderAsPdfCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schema.tenseventynine.com/PresentableServices/DocumentConverter/2011/05/Re" +
            "nderAsPdf", RequestNamespace="http://schema.tenseventynine.com/PresentableServices/DocumentConverter/2011/05", ResponseNamespace="http://schema.tenseventynine.com/PresentableServices/DocumentConverter/2011/05", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] RenderAsPdf([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] docBinary, string fileNameWithExt) {
            object[] results = this.Invoke("RenderAsPdf", new object[] {
                        docBinary,
                        fileNameWithExt});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void RenderAsPdfAsync(byte[] docBinary, string fileNameWithExt) {
            this.RenderAsPdfAsync(docBinary, fileNameWithExt, null);
        }
        
        /// <remarks/>
        public void RenderAsPdfAsync(byte[] docBinary, string fileNameWithExt, object userState) {
            if ((this.RenderAsPdfOperationCompleted == null)) {
                this.RenderAsPdfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRenderAsPdfOperationCompleted);
            }
            this.InvokeAsync("RenderAsPdf", new object[] {
                        docBinary,
                        fileNameWithExt}, this.RenderAsPdfOperationCompleted, userState);
        }
        
        private void OnRenderAsPdfOperationCompleted(object arg) {
            if ((this.RenderAsPdfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RenderAsPdfCompleted(this, new RenderAsPdfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RenderAsPdfCompletedEventHandler(object sender, RenderAsPdfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RenderAsPdfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RenderAsPdfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591